# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N-PAWb7ZzQdozYWn7n9FeUGPmn86vUgG
"""

while True:
  numero = int(input('Digite o primeiro número: '))
  numero_2 = int(input('Digite o segundo número: '))
  operação_matematica = (input('Escolha a operação (+, -, *, /) ou digite ''sair'' para encerrar.'))

  if operação_matematica == '+':
    print ('O resultado é: ', numero + numero_2)

  elif operação_matematica == '-':
    print ('O resultado é: ', numero - numero_2)

  elif operação_matematica == '*':
    print ('O resultado é: ', numero * numero_2)

  elif operação_matematica == '/':
    if numero_2 != 0:
      print ('O resultado é: ', numero / numero_2)
    else:
      print ('Não é possível dividir por zero')
  elif operação_matematica == 'sair':
    print ('Obrigado por usar a calculadora!')
    break

